version: 0.0
os: linux

files:
  - source: .
    destination: /home/ubuntu/app/back
    file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
