version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - chmod +x back/gradlew

  build:
    commands:
      - cd back
      - ./gradlew clean build -x test
      - cd ..

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - back/build/libs/*.war
